### ISSUE TITLE
마이 페이지 마크업

### ISSUE THREAD

**Issue by Samuel-0930** [FRONTENDSCHOOL8/Book-Kong#65]

**Comment by DragonTiger92** [comment]
@HHeoGeon 이 이슈에서 스타일도 같이 해결한 다음 이슈 닫는 걸로 알고 있는데, 지금 배포 버전이랑 origin - develop 버전 마이 페이지 캐릭터 구현 부분 CSS 안 돼있는 거는 이 이슈 닫기 전에 해결할 거지???

**Comment by DragonTiger92** [comment]
작업 완료 by @HHeoGeon
