### ISSUE TITLE
아이디 저장 기능 구현

### ISSUE THREAD

**Issue by Samuel-0930** [FRONTENDSCHOOL8/Book-Kong#86]

**Comment by DragonTiger92** [comment]
현재 웹앱의 특성 상 브라우저를 이용하여 로그인 기능을 제공하는데 브라우저 자체에서 아이디 저장 기능을 제공하고 있으며, 우리 앱에서는 사용자가 자의로 로그아웃을 하기 전까지 로그인이 계속 되어 있으므로 본 이슈가 현재 backlog로 등록 되어 있을 필요가 없다고 생각 되어 issue를 닫음.
